services:
  - type: web
    name: multimodal-pdf-chat
    env: python
    buildCommand: |
      # Make setup script executable and run it
      chmod +x setup.sh
      ./setup.sh
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: TESSDATA_PREFIX
        value: /usr/local/share/tessdata
      - key: PATH
        value: /usr/local/bin:${PATH}
    disk:
      name: pdf-data
      mountPath: /data
      sizeGB: 1 