services:
  - type: web
    name: multimodal-pdf-chat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
    disk:
      name: pdf-data
      mountPath: /data
      sizeGB: 1 