services:
  - type: web
    name: multimodal-pdf-chat
    env: python
    buildCommand: |
      # Install system dependencies with sudo
      sudo apt-get update
      sudo apt-get install -y tesseract-ocr tesseract-ocr-eng
      # Verify tesseract installation
      tesseract --version
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
    disk:
      name: pdf-data
      mountPath: /data
      sizeGB: 1 